### ISSUE TITLE
Add support for top level await?

### ISSUE THREAD

**Issue by PandawanFr** [axetroy/vscode-deno#10]
Top level await support [seems to have been added to TypeScript](https://github.com/microsoft/TypeScript/pull/35813) but I still get errors in VSCode. 

![image](https://user-images.githubusercontent.com/8564550/73139508-8bb2b800-4023-11ea-8ed3-4be276ed0739.png)

I'm not sure if this is a TypeScript issue or an issue with this extension (or perhaps a mismatch with TypeScript versions, etc.)

**Comment by David-Else** [comment]
TypeScript 3.8rc with top level await is coming to VS Code in the next version. You can use the latest dev version of TypeScript in VS Code, but I don't know if this extension supports that?

Less than a week till the next VS Code stable version anyway :)

https://github.com/microsoft/vscode/issues/87479
> TypeScript/JavaScript
> 
> red_circle running_man Adopt TS v3.8 RC @mjbvz

**Comment by axetroy** [comment]
![截屏2020-01-2920 56 27](https://user-images.githubusercontent.com/9758711/73358628-04db3500-42da-11ea-8c76-6a385bd75249.png)

This should have been resolved, waiting for the release of a later version

**Comment by Discreater** [comment]
Is it solved? I still get this error message.
![批注 2020-03-17 214330](https://user-images.githubusercontent.com/41231596/76863412-695a4f80-689a-11ea-924f-c668d5a51085.png)
```
VSCode version: 1.43.0
TS version: 3.8.3
deno version: 0.36.0
axetroy.vscode-deno version: 3.3.0
```
