### ISSUE TITLE
Triple-Slash Directive does not work

### ISSUE THREAD

**Issue by KSXGitHub** [axetroy/vscode-deno#102]
### test

**Describe the bug**

Deno itself recognizes triple-slash directive that specifies type definitions, but the plugin does not.

**To Reproduce**

Create a TypeScript file that imports 'https://deno.land/x/once/index.js' and hover mouse cursor over it to make IntelliSense appears. For example:

```typescript
export { once } from 'https://deno.land/x/once/index.js'
```

**Expected behavior**

The IntelliSense pop-up should show type definition as it was defined in https://deno.land/x/once/index.d.ts with generic parameters, but it displays `any` instead.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/11488886/77179206-b9375180-6afa-11ea-8b16-1e3c1b7d5fb8.png)

**Versions**

vscode: 1.43.1
deno: 0.36.0
extension: 3.3.0

**Comment by axetroy** [comment]
It's not a bug for the extension.

This is a problem with Deno because it does not download the `./index.d.ts` file

```bash
$ deno fetch https://deno.land/x/once/index.js --reload
Download https://deno.land/x/once/index.js
```

It can be seen here that it only downloaded `https://deno.land/x/once/index.js` and did not download `https://deno.land/x/once/index.d.ts`

**Comment by KSXGitHub** [comment]
> This is a problem with Deno because it does not download the `./index.d.ts` file

[It actually does](https://user-images.githubusercontent.com/11488886/77418917-2815f280-6dfa-11ea-816e-c5713f683a31.png), but the language server still shows `any`.

**Comment by KSXGitHub** [comment]
Further more, intentionally assigning the wrong type results in error when run `deno run` but the editor display no error:

```typescript
import once from 'https://deno.land/x/once/index.js'
const f = once(Math.random) // => `() => number` in Deno but `() => any` in the editor
const n: string // => compile error when run `deno run` but nothing appears in the editor
```

It might be Deno's fault to not fetch `index.d.ts`, but once it does, Deno works as expected, unlike the language server which still refuses to find `index.d.ts`. Therefore, I think this is not Deno problem alone.

**Comment by axetroy** [comment]
@KSXGitHub confirm!

BTW. I recommend you use typescript to write your lib instead of javascript

**Comment by KSXGitHub** [comment]
> BTW. I recommend you use typescript to write your lib instead of javascript

I would for more complex code. But `once` is simple enough that I can write it in JavaScript and have browser support out-of-the-box for free so why wouldn't I.

**Comment by axetroy** [comment]
![1](https://user-images.githubusercontent.com/9758711/77730294-77973100-703b-11ea-8fa8-f4db34a3909d.gif)

This issue has been fixed although not perfect

Waiting for the next version update

**Comment by KSXGitHub** [comment]
> although not perfect

What's the flaw?

BTW, you are supposed to pass a function to `once`, not a value, e.g. `once(() => 123)` instead of `once(123)`.

**Comment by axetroy** [comment]
@KSXGitHub 

This is just an example that showing consistent with Deno's errors

![截屏2020-03-2715 29 32](https://user-images.githubusercontent.com/9758711/77732607-276e9d80-7040-11ea-9881-237a53f353a6.png)
![截屏2020-03-2715 30 24](https://user-images.githubusercontent.com/9758711/77732616-2a698e00-7040-11ea-9465-09a22af4f40d.png)

> What's the flaw?

The disadvantage is that there can only be one Triple-Slash Directive in a js/ts file.

Because this is a typescript plugin with limited functionality, and the plugin does not expose the `addReferencedFilesToTypeDirective` method

I am exploring if solved, maybe soon

**Comment by KSXGitHub** [comment]
> The disadvantage is that there can only be one Triple-Slash Directive in per js/ts file.

That's enough for me for now.

**Comment by axetroy** [comment]
I closed the issue since the new version have been released

If there are other issues, feedback is welcome

**Comment by KSXGitHub** [comment]
@axetroy  It seems that `x-typescript-types` stopped working. Is this issue related?
