### ISSUE TITLE
Unable to resolve local imports defined in import map

### ISSUE THREAD

**Issue by dev-nicolaos** [axetroy/vscode-deno#103]
### Environment
- OS: Windows 10 Home v1909
- Visual Studio Code: 1.43.0
- vscode-deno: 3.3.0
- deno: 0.36.0

### Steps To Reproduce
1. Clone [bug example repo](https://github.com/dev-nicolaos/vscode-deno-importmap-bug) (minimal reproducible example)
1. In the root folder, run and `deno --importmap=import_map.json src/mod.ts` `deno --importmap=import_map.json src/mod.ts -a`
1. Observe that the program runs as expected
1. In Visual Studio Code, open `src/mod.ts`

### Current Behavior
The extension cannot resolve imports which point to local modules (as defined in `import_map.json`) and display error 1004

### Expected behavior
The extension sees the local relative path the module is referring to in `import_map.json` and resolves the import. VS code no longer shows a red underline under the specifier and Intellisense works correctly. 

### Screenshots
![image](https://user-images.githubusercontent.com/29005473/77181510-ac7a1580-6a88-11ea-9d95-d76dff1b3c4b.png)

![image](https://user-images.githubusercontent.com/29005473/77181562-c3b90300-6a88-11ea-84b2-8c85ae8982ee.png)

### Notes
This bug seems to be present regardless of...
- whether the import is a named or a default import
- whether the specifier ends with a slash or not
- whether the path refers to a file or a folder
- whether the files are TS or JS (not shown in repo but have tried)
- whether the path is relative (`./...`) or absolute (`/...`) (not shown in repo but have tried)

**Comment by axetroy** [comment]
Hi. I have fixed this issue in the new version v3.4.0.

try again. if you still got this. reopen the issue.

**Comment by dev-nicolaos** [comment]
Works great! Thanks for the hard work you've put into this extension.
