### ISSUE TITLE
a comparison between vs-code extensions? if possible.

### ISSUE THREAD

**Issue by Nothing-Works** [axetroy/vscode-deno#116]
I'm very new to deno, and very interested in it. When it comes to vs-code extensions, I can see there are 3 in the marketplace(correct me if I'm wrong).

Any chance that someone can explain the differences between these 3? Or do a comparison if you can. And some recommendations if I'm not asking too much!

1. [by ameerthehacker](https://marketplace.visualstudio.com/items?itemName=ameerthehacker.deno-vscode)

2. [by justjavac](https://marketplace.visualstudio.com/items?itemName=justjavac.vscode-deno)

3. [by axetroy](https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno)

**Comment by David-Else** [comment]
This is the only serious extension now, the others were abandoned and this is now considered the 'official' extension.

It would be great if the other ones could be marked as archived and link to this one, would save a lot of wasted time.

**Comment by axetroy** [comment]
Thanks to someone who has already answered this question

BTW, This is not an official extension. But it is currently the only available extension for using, and I am willing to spend time to maintain.

If there is no problem, I will close this issue.
