### ISSUE TITLE
do not allow import module which not end with /.tsx?/

### ISSUE THREAD

**Issue by axetroy** [axetroy/vscode-deno#12]
![截屏2020-01-2920 53 37](https://user-images.githubusercontent.com/9758711/73358377-736bc300-42d9-11ea-8f8f-cb02717264aa.png)

```ts
// valid
import * as path1 from "https://deno.land/std/path/mod.ts";
import * as react from "https://deno.land/std/react/mod.tsx";

// invalid
import * as path2 from "https://deno.land/std/path/mod";
import * as path3 from "https://deno.land/std/path/mod.js";
```

This should not be allow.

**Comment by brandonkal** [comment]
Merging this in as is seems like a mistake. It is generally helpful but ESM imports don't require the file to have an extension. If it is a remote file, it is very possible that an extension does not exist.

**Comment by axetroy** [comment]
@brandonkal 
Thanks for your feedback.

I will continue to investigate whether this should be done.

re-open issue

**Comment by axetroy** [comment]
Hi!
Could you give me an example for this?

**Comment by brandonkal** [comment]
Sure. JSPM serves JavaScript modules without extension:
https://dev.jspm.io/react

Also, while Deno does not handle it gracefully, query parameters are valid after the extension in the URL.

Also, something like this makes more sense as an ESLint rule, not an editor extension. That would give people the option to configure (i.e. set hosts that serve without an extension, comment to disable a certain line, etc)

With Deno programs, no extension generally means an error but it is not a hard rule. Therefore a linter is where it should be.

**Comment by axetroy** [comment]
#37 As the Feature `import ecma module` land

So currently it is not mandatory to have an extension
