### ISSUE TITLE
@deno-types is not working?

### ISSUE THREAD

**Issue by shian15810** [axetroy/vscode-deno#122]
**Describe the bug**

I have a file named `semver.ts` with the following content:

```typescript
// @deno-types="./semver.d.ts"
import semver from 'https://dev.jspm.io/semver';

semver.clean('v1.0.0');
```

And also a file named `semver.d.ts` with the following content:

```typescript
interface Options {
  loose?: boolean;
  includePrerelease?: boolean;
}

declare function clean(
  version: string,
  optionsOrLoose?: boolean | Options,
): string | null;

export { clean };
```

However, I'm getting this:

![Screen Shot 2020-04-03 at 7 44 23 PM](https://user-images.githubusercontent.com/22716548/78357234-a422ee00-75e3-11ea-8568-9a835f0fc76a.png)

However, I can run `deno semver.ts` with no problem.

**Expected behavior**

Type of `semver.clean` should be inferred from `semver.d.ts` through `@deno-types`.

**Versions**

vscode: 1.43.2
deno: 0.38.0
extension: 3.4.1

**Comment by shian15810** [comment]
I see https://github.com/axetroy/vscode-deno/issues/68 has already added this feature, but it is not working?

**Comment by axetroy** [comment]
Currently I have no plans to support @deno-types

See the readme

> This will not be implemented in then extensions.

**Comment by shian15810** [comment]
Is there a reason why?

Or maybe I could be of help?

**Comment by KSXGitHub** [comment]
There is a better alternative for you: [cdn.pika.dev](https://cdn.pika.dev) support TypeScript definition for Deno out-of-the-box via `x-typescript-types`.

**Comment by axetroy** [comment]
@shian15810 

There are several reasons:

### 1. No Javascript

I encourage people to use typescript instead of javascript

If you must use javascript, then use some can return `x-typescript-types` cdn. eg cdn.pika.dev

### 2. work with typescript plugin

There is currently no way to work well with the typescript plugin (as I known)

If so, you are welcome to read the source code (it is actually not difficult) and sned a PR

**Comment by shian15810** [comment]
@KSXGitHub Thanks for recommending it, but I would rather use `semver` on npm, which is guaranteed to be heavily maintained, since our organization requires review on dependencies quality.

@axetroy Agreed with point 1, but going forward with this decision will eventually narrow the options for users to choose which vendor to import javascript from, which in this case means only https://pika.dev.

Also one more scenario for this is that people often extends the types in global scope to cater to their needs, be it required by third party library, or correcting wrong types provided by library, or to maintain legacy codes.

**Comment by shian15810** [comment]
To publish a typescript package on npm, one is required to transpile it into javascript. Since it is written in typescript, and deno supports typescript right away, it makes sense to just directly import the raw typescript source from github/gitlab/bitbucket.

However in reality, this won't work since deno doesn't support relative file import without file extension, which is the correct way of doing it, but sadly this is not what almost everyone else is doing it.

Also in this scenario, `// @deno-types="./foo.d.ts"` will be very useful.

**Comment by KSXGitHub** [comment]
@shian15810 If you insist on jspm.io, I suggest you should create a JavaScript wrapper that has triple-slash directive, for example:

```javascript
/// <references types="semver.d.ts" />
export * from 'https://dev.jspm.io/semver'
export { default } from 'https://dev.jspm.io/semver'
```

**Comment by axetroy** [comment]
I rethought the compile hint and I decided to implement it

see #129 

It will land in soon

**Comment by shian15810** [comment]
Thanks for the amazing work!
