### ISSUE TITLE
Property 'entries' does not exist on type 'ObjectConstructor'

### ISSUE THREAD

**Issue by Soremwar** [axetroy/vscode-deno#13]
By trying the following code I get a warning over Object.entries

```typescript
const message: Array = Object.entries({"a" : 1});
console.log(message);
```

By googling a little it seems that the problem is related to the compiler options used in the TS compiler that parses the code.

**Comment by axetroy** [comment]
The function signature you are using is incorrect

try this.

```ts
const message: [string, number][] = Object.entries({ a: 1 });
console.log(message);
```

And it has nothing to do with `vscode-deno`

So I closed this issue.

Thx.
