### ISSUE TITLE
Getting this error: Could not find `deno` in your $PATH. Please install `deno`, then restart the extension.

### ISSUE THREAD

**Issue by mudgen** [axetroy/vscode-deno#134]
**Describe the bug**

I installed the extension.  When I enable the extension I get this error:
"Could not find `deno` in your $PATH. Please install `deno`, then restart the extension."

I looked at my $PATH and I see this in it: "C:\Users\mudge\\.deno\bin"

I look in there and I find this file: "deno.exe".   So it looks to me that deno is in my path.  Or is it failing because of the "exe" extension?

I am using Windows 10.
I am using vscode-den version 3.5.1
I am using deno version 0.40.0
I am using vscode version 1.44.0

Also, the "deno" command works just find on my command line which tells me that "deno" is in my path.

I am eager to get this extension working because it is so useful. It is not working with this error.

Here is my .vscode/settings.json file:
```
{
    "deno.enable": true,
    "[typescript]": {
        "editor.defaultFormatter": "axetroy.vscode-deno"
      }
}
```

**To Reproduce**

1, Use Windows 10.
2. Install deno.
2. Install the extension or enable it.

**Comment by axetroy** [comment]
Please confirm which shell you use in vs code?

`cmd.exe` or `PowerShell` or `git bash`?

Make sure that `deno` can be found in the shell $PATH

**Comment by mudgen** [comment]
Thank you.  I closed vscode and then started it again. Now it works.  Thanks for your help.

Thanks again!
