### ISSUE TITLE
tsconfig.json with this extension

### ISSUE THREAD

**Issue by mudgen** [axetroy/vscode-deno#136]
How can I use tsconfig.json with this extension?

I put a tsconfig.json at the root of my project but the extension doesn't seem to be picking it up.

Thanks

**Comment by axetroy** [comment]
By default, typescript will automatically detect the configuration file

see the log

![截屏2020-04-1014 24 39](https://user-images.githubusercontent.com/9758711/78968397-0d03ec00-7b37-11ea-8e76-39f6435338f7.png)

Can you describe what is not working?

**Comment by mudgen** [comment]
I put the following in my tsconfig.json file but it isn't working:
```
{
  "strictNullChecks": false,
  "noImplicitAny": false
}
```

My tsconfig.json file is at the root of my file.

Which log are you showing?

My typescript log just shows this:
```
[Info  - 15:37:46.384] Using tsserver from: c:\Users\mudge\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 15:37:46.390] <syntax> Forking...
[Info  - 15:37:46.396] <syntax> Starting...
[Info  - 15:37:46.398] <semantic> Forking...
[Info  - 15:37:46.404] <semantic> Starting...
```

I looked in the "Log (Extension Host)" log and all the other logs  but I didn't see anything in there about tsconfig.json.

**Comment by mudgen** [comment]
I got it working by using the right json for the configuration file. Which is this:
```
{
  "compilerOptions": {
    "strictNullChecks": false,
    "noImplicitAny": false
  }
}
```

**Comment by axetroy** [comment]
This looks ok.

Thx for your feedback. I close this issue
