### ISSUE TITLE
Support for Javascript

### ISSUE THREAD

**Issue by mudgen** [axetroy/vscode-deno#139]
It would be really useful if the plugin supported pure Javascript.  Files with the "js" extension.

I am porting a lot of javascript-based nodejs code to deno.  Having a Javascript linter that worked with Deno would make this work a lot easier.

Trying to convert all the js to typescript is not a good option because Typescript gives so many errors for things that are valid in javascript, and it is too much work to convert it all to Typescript when dealing with a lot of code to port.

**Comment by axetroy** [comment]
Sorry. I don't understand what does it mean "Support for Javascript"

Can you describe what do you want?

**Comment by mudgen** [comment]
I want a linter in vscode for javascript that works with deno.

**Comment by mudgen** [comment]
I would like the same features this plugin supports for TypeScript to also work using Javascript.   Specifically I want to use the ".js" extension and I want all the TypeScript specific errors to go away, like "The property 'getBBox' does not exist on value of type."

**Comment by mudgen** [comment]
I am currently using ESLint with vscode which almost works with deno.   It complains about top level await,  which is valid in deno.

**Comment by axetroy** [comment]
This feature is out of scope

you can track the linter at here https://github.com/denoland/deno_lint
