### ISSUE TITLE
Better import map detection

### ISSUE THREAD

**Issue by shian15810** [axetroy/vscode-deno#141]
**Describe the bug**

Scenario 1:

Following example from https://github.com/WICG/import-maps#packages-via-trailing-slashes with the trailing slash entry at the bottom.

import_map.json
```json
{
  "imports": {
    "deno_std:log": "https://deno.land/std@v0.40.0/log/mod.ts",
    "deno_std:log/": "https://deno.land/std@v0.40.0/log/",
  }
}
```

The extension is ignoring `"deno_std:log/"`.

![Screen Shot 2020-04-14 at 3 32 10 PM](https://user-images.githubusercontent.com/22716548/79198020-5f117e00-7e65-11ea-9f41-1703d32fa83a.png)

Scenario 2:

Simply flipping the order.

import_map.json
```json
{
  "imports": {
    "deno_std:log/": "https://deno.land/std@v0.40.0/log/",
    "deno_std:log": "https://deno.land/std@v0.40.0/log/mod.ts",
  }
}
```

The extension has no problem detecting both.

![Screen Shot 2020-04-14 at 3 41 08 PM](https://user-images.githubusercontent.com/22716548/79198678-7309af80-7e66-11ea-8ec0-d9390c704487.png)

Both of these scenarios have no issue with `deno --importmap`.

**Expected behavior**

Spec wise, the extension should detect the trailing slash in import map regardless of order of entry.

**Versions**

vscode: 1.44.0
deno: 0.40.0
extension: 3.5.1

**Comment by shian15810** [comment]
Anything wrong?

**Comment by shian15810** [comment]
https://github.com/WICG/import-maps#packages-via-trailing-slashes

> Import maps do this by giving special meaning to specifier keys that end with a trailing slash.

Which means `imports` **key** that ends with a trailing slash must also have its corresponding **value** ends with a trailing slash, otherwise it is not valid.

If possible, I will send a PR later.

**Comment by axetroy** [comment]
@shian15810 it's mistake to close this issue.

yeah. If you can send a PR, that must be excellent
