### ISSUE TITLE
Auto import does not format inserted import properly

### ISSUE THREAD

**Issue by David-Else** [axetroy/vscode-deno#155]
```ts
// deps.ts
export {
  assert,
  assertEquals,
  assertStrictEq,
} from "https://deno.land/std@v1.41.0/testing/asserts.ts";
```
Auto import does not format inserted import properly

finish typing `assert` and let it auto import, see results in attached image
```ts
let greeter: HTMLElement | null = document.getElementById("greeter")!; // Please forgive the Non-Null Assertion Operator for this example
a // type assert so it can auto import
greeter.innerText = "Hello world!";
```
![Screenshot from 2020-04-22 13-03-52](https://user-images.githubusercontent.com/12832280/79980061-6a366080-849a-11ea-96d3-3836ef9a8675.png)

vscode: latest
deno: 0.41.0
extension: 3.6.1

**Comment by axetroy** [comment]
This is the default behavior of vscode, I don’t know it is a bug.

Even if the `vscode-deno` extension is not enabled, vscode will have this problem, it will not format the text automatically which will be inserted.

**Comment by David-Else** [comment]
OK, will close the issues then. Thanks.
