### ISSUE TITLE
import map pointing to json file no longer working

### ISSUE THREAD

**Issue by btrauma8** [axetroy/vscode-deno#172]
import map used to allow pointing to a local json file (not a local ts file).
but now it gives red squiggles.
however, it does work when running deno.
screenshot shows all relevant files.

![image](https://user-images.githubusercontent.com/4399964/81071804-d2c60a00-8eaa-11ea-8ce2-19a12be3aca0.png)

**Comment by btrauma8** [comment]
i rewrote my import map to point to a ts file which then reads the json file and exports what i need...so, it's easy to work around. but i think something broke importmap pointing to json files directly.

**Comment by axetroy** [comment]
see changlogs. No longer support import JSON statment.

**Comment by btrauma8** [comment]
oh! wow, didn't realize 1rc1 was out. i'll update. thanks!
