### ISSUE TITLE
Extension 1.10.1 is registering as a formatter for markdown now

### ISSUE THREAD

**Issue by David-Else** [axetroy/vscode-deno#20]
I have prettier extension installed and VS Code alerted me I had two formatters installed, prettier and deno, and asked me to choose one. For a while it was very confused and there was a lag when I pressed save before it formatted. 

This happened just after your new 1.10.1 release... there is no mention of formatting options in the README? I thought the Deno formatting was going to be optional? Cheers!

**Comment by axetroy** [comment]
`1.10.x` previous versions also support markdown formatting.

There are no breaking changes

The deno formatter is always be optional.

If multiple formatter are installed. You need to choose one as the default formatter.

> there was a lag when I pressed save before it formatted.

Because deno formatter calls std @ {deno_version} / prettier

So every time you upgrade deno, it will re-fetch dependencies, maybe it will take a minute

**Comment by axetroy** [comment]
In a future release, prefetch formatter dependencies may be considered

**Comment by David-Else** [comment]
Deno is switching to the built in rust `dprint` formatter, so there should be no need to fetch any dependencies in the future :)

https://dprint.dev/

I don't think it works with Markdown yet, so this needs looking into... I just saw this in the latest commits, I don't have any actual information, best ask @bartlomieju

https://github.com/denoland/deno/pull/3820
https://github.com/denoland/deno/commit/73a3cc21d0e7ceec1275078db125f57ce97725fb

**Comment by axetroy** [comment]
deno v0.32.0 have land `dprint` for `deno fmt`

working on this.

**Comment by David-Else** [comment]
https://github.com/denoland/deno/issues/3877 is closed, you can probably close this issue.

I estimate Deno v0.33.0 should be out very soon with this included :)
