### ISSUE TITLE
Hide 1103 (Top Level Await)

### ISSUE THREAD

**Issue by brandonkal** [axetroy/vscode-deno#25]
A 'for-await-of' statement is only allowed within an async function or async generator.
The other error is hidden by the extension. It would be nice to see this one hidden as well.

**Comment by axetroy** [comment]
Ignoring errors at the moment is not always a solution

I am waiting for the release of typescript@3.8, and it should no longer have this problem when the built-in version of vscode is 3.8

**Comment by brandonkal** [comment]
That's fair, but it seems odd to be selective here.

**Comment by axetroy** [comment]
typescript 3.8 have land with vscode 1.43.0

It solved top-level await

But unfortunately `for-await-of` is not supported

I will ignore this error in the new version

So I temporarily closed this issue and reopened it if it still exists
