### ISSUE TITLE
[bug] cannot find module if redirected

### ISSUE THREAD

**Issue by brandonkal** [axetroy/vscode-deno#27]
As the title says, TS complains when a file has a redirect.

```ts
import metallbCRD from 'https://js.bkal.workers.dev/google/metallb/v0.8.3/manifests/metallb.yaml.js'
console.log(metallbCRD)
```

**Comment by axetroy** [comment]
BUG FIXED. Thx for feedback and I will release a new version later

![截屏2020-02-0422 12 45](https://user-images.githubusercontent.com/9758711/73752366-d1961b80-479b-11ea-8b2e-0e5f2301e35d.png)

**Comment by brandonkal** [comment]
@axetroy Thank you for looking into this. Unfortunately, I am still seeing this bug (same resource). I see you've tagged the commit in 1.19.0 which is what I have installed. I'm on Linux.

**Comment by brandonkal** [comment]
Deno 0.32.0

**Comment by axetroy** [comment]
Can you provide the above source code

I can't find it

**Comment by brandonkal** [comment]
@axetroy Yes, I've added code to my original post here.

**Comment by axetroy** [comment]
I'm sure it works fine on macOS

It's not clear why it doesn't work on Linux

Unfortunately, I don't have a Linux environment

![1](https://user-images.githubusercontent.com/9758711/74101773-6754f080-4b78-11ea-88f5-38f5499b9efd.gif)

**Comment by axetroy** [comment]
Are you sure you have fetched this module?

```shell
$ deno fetch https://js.bkal.workers.dev/google/metallb/v0.8.3/manifests/metallb.yaml.js
```

**Comment by brandonkal** [comment]
Yes. The code executes fine.

**Comment by brandonkal** [comment]
It is now working in 1.21.0 after several VSCode restarts. Thanks again!
