### ISSUE TITLE
support import map

### ISSUE THREAD

**Issue by axetroy** [axetroy/vscode-deno#3]
Since there is currently no standard import-map.json name

So you can only specify a file through the configuration of vscode

```json5
// .vscode/setting.json
{
  "deno.importMap": "./relative/your/project/path" // relative or absolute filepath
}
```

**Comment by axetroy** [comment]
all most done


![截屏2020-02-0600 25 15](https://user-images.githubusercontent.com/9758711/73861103-84877780-4877-11ea-9dae-28532e650156.png)
![截屏2020-02-0600 27 43](https://user-images.githubusercontent.com/9758711/73861115-8b15ef00-4877-11ea-92a2-71671cd30a2f.png)


```json
{
  "imports": {
    "http/": "https://deno.land/std@v0.23.0/http/"
  }
}
```

**Comment by David-Else** [comment]
Awesome! It would be very helpful if you were to add this example to the README, and a link to https://deno.land/std/manual.md#import-maps
