### ISSUE TITLE
Feature request: publish deno-language-server to npm？

### ISSUE THREAD

**Issue by fannheyward** [axetroy/vscode-deno#34]
I've did [coc-deno](https://github.com/fannheyward/coc-deno), a coc.nvim extension fork from [justjavac.vscode-deno](https://github.com/justjavac/vscode-deno) that provide Deno support for vim/neovim. I'd like to use your deno-language-server to make more features. Can you publish it to npm?

**Comment by axetroy** [comment]
interesting

But this typescript plugin currently only serves vscode

It's not ready for publish to npm, but it's planned

**Comment by axetroy** [comment]
Sorry, publish to npm means more responsibility

But I'm not ready for this yet
