### ISSUE TITLE
Document update for Config using VS Code 1.42 and TS 3.8rc

### ISSUE THREAD

**Issue by David-Else** [axetroy/vscode-deno#36]
Hi, I see the new version disables using the workspace version of TS and makes the new VS Code mandatory.

Code 1.42 supports all the new TS 3.8 features (but has old 3.7.5 built in), and TS 1.38rc was just released. I think this RC is the best version to use for the next month before the new VS Code.

I can't see any instructions on how to enable it in the README file, so I have:

```
pnpm install -g typescript@rc
```
(main file, global settings.json in vs code)
```
"typescript.tsdk": "/home/user/.nvm/versions/node/v12.15.0/pnpm-global/3/node_modules/typescript/lib"
```
Now I have `3.8.1rc` showing up as the built in VS Code version.

Is this correct for your extension? Maybe add to the README? Cheers!

**Comment by axetroy** [comment]
I am using vscode insider.

current vscode version 1.43.0 with typescript 3.8.0-dexxxxx

Actually, I don't have version 1.42.0 installed

Can you check the typescript version of vscode 1.42.0

**Comment by David-Else** [comment]
> Can you check the typescript version of vscode 1.42.0

It has `TypeScript  3.7.5` built in to 1.42.0, but you can change it to the latest version globally using `"typescript.tsdk"`... is this supported with your extension? I hope so :)

**Comment by axetroy** [comment]
Changing global typescript is a bad idea

This is my mistake, I use vscode insider which is typescript 3.8

And vscode 1.42.0 still uses typescript 3.7.5

**Comment by axetroy** [comment]
This will cause the top-level await of extension 1.18.0 just released to fail

Rolling back with new release

**Comment by David-Else** [comment]
I would like to use the stable VS Code and the latest (almost stable) `TypeScript 3.8.1rc`.

I hope your rollback won't stop this working, it seems like the best solution until the next stable VS Code. Cheers.

**Comment by David-Else** [comment]
The official way to use the latest TS in VS Code is to use the https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next , I just prefer the RC as I am sick of all the bugs wasting my time.

**Comment by axetroy** [comment]
In theory, of course it supports custom global typescript.

We don't need to install additional typescript

Rollback completed and I closed this issue

Thx.
