### ISSUE TITLE
Deno Language Server still running when disabled

### ISSUE THREAD

**Issue by PandawanFr** [axetroy/vscode-deno#38]
I currently have a multi-project workspace in TypeScript (but not using deno). Even after adding `"deno.enable": false` in my `.code-workspace` config file, I still see the deno language server running and I get the following error when saving (I have auto format on save enabled).

```
Formatting 'file:///Users/panda/Dev/web/yave/example/src/index.ts' at /Users/panda/Dev/web/yave/example
Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: error: Found argument '--stdin' which wasn't expected, or isn't valid in this context

USAGE:
    deno run --allow-read=<allow-read>

For more information try --help

  Code: -32603 
```

**Comment by axetroy** [comment]
can you provider more information. like extension/vscode version

BTW. currently, `Deno Language Server` always exist once the extension is activated

**Comment by PandawanFr** [comment]
uh sure
Deno: 0.29.0
Deno Extension: 1.19.0
VSCode: 1.42.0

The extension itself is activated but I have `"deno.enable": false`. 
![image](https://user-images.githubusercontent.com/8564550/74058590-37042b00-499b-11ea-9322-458acd978e71.png)

**Comment by axetroy** [comment]
Deno updated parameter resolution in new version

So upgrading Deno will not have this problem

> EDIT: I updated deno to 0.32.0, it no longer errors out, but it still formats everything even though the extension is disabled... Is that intended?

Yes. it's intended

`deno.enable`= `false` will disabled related features of Deno

But keep formatting tools

So I closed the issue

If other problems are found, feedback is welcome
