### ISSUE TITLE
Allow imports with .ts especially from deno.land

### ISSUE THREAD

**Issue by Skillz4Killz** [axetroy/vscode-deno#41]
**Describe the bug**
Unable to import from deno.land......ts paths.

**To Reproduce**

1. Try to import `https://deno.land/std/ws/mod.ts`

**Expected behavior**

Read it as a valid import path and hide the typescript error.

**Screenshots**

![image](https://user-images.githubusercontent.com/23035000/74105288-74e38980-4b2a-11ea-9d86-00ce0b9bf314.png)

![image](https://user-images.githubusercontent.com/23035000/74105265-4796db80-4b2a-11ea-94d2-7e6751a9c392.png)

**Versions**

vscode: Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.5.0
deno: 0.32.0
extension: 1.19

**Comment by lucacasonato** [comment]
This is because you hadn't fetched the file using `deno` or `deno fetch`. The extension should probably give a better error message though.

**Comment by axetroy** [comment]
Looks strange, this problem should not exist

**Comment by axetroy** [comment]
Extensions do provide the information when the module does not exist

![截屏2020-02-1001 40 43](https://user-images.githubusercontent.com/9758711/74106956-633fc780-4ba6-11ea-9745-e322435fbb86.png)

**Comment by lucacasonato** [comment]
Oh that's awesome. It's that in the currently released version of the module?

**Comment by axetroy** [comment]
@lucacasonato yes. The current version is supported

**Comment by lucacasonato** [comment]
Ah I see - just tried it out - it's great! :smiley:. I don't know why it was not working for @Skillz4Killz - he is on 1.19.0 according to the issue report. Weird...

**Comment by axetroy** [comment]
This should be resolved, please upgrade the extension.

If this problem still exist, please reopen the issue

**Comment by Skillz4Killz** [comment]
@axetroy This is happening again

**Comment by axetroy** [comment]
@Skillz4Killz 
Try change the textDocument's content and wait for typescript recompile

If the problem still exist, reopen the issue
