### ISSUE TITLE
Auto-Import Uses Local Version Instead of Deno.Land URL

### ISSUE THREAD

**Issue by Skillz4Killz** [axetroy/vscode-deno#44]
**Describe the bug**
When autoimporting something, it will use the local version as opposed to importing it from the deno.land url. This becomes a problem as deploying this code would require all users of the lib to have the exact same file path.

**To Reproduce**

1. Use VSC Autoimport
![image](https://user-images.githubusercontent.com/23035000/74109210-8b500c00-4b4f-11ea-8025-0775d2fbb686.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/23035000/74109203-812e0d80-4b4f-11ea-8401-4c314db898ab.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/23035000/74109216-986cfb00-4b4f-11ea-8f5f-ce6a49603357.png)

**Versions**

vscode: Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:33.119Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.5.0
deno: 0.32.0
extension: 1.19.0

**Comment by axetroy** [comment]
I don't quite clear what is happening with this

![1](https://user-images.githubusercontent.com/9758711/74125480-640d4380-4c10-11ea-8edb-90d98ebbbe28.gif)

**Comment by Skillz4Killz** [comment]
Try and import the `WebSocket` type without having anything in the file. Sorry about quality my first gif:

https://giphy.com/gifs/XG0L6wUUauVGC3oMKx

**Comment by axetroy** [comment]
I tried the same operation, but it was like this

![1](https://user-images.githubusercontent.com/9758711/74177293-6e612900-4c74-11ea-806e-6618c26199ea.gif)

Is the auto-import function provided by vscode or a third-party extension?

If it is provided by vscode, can you tell me where to enable it, I don't know much about this

**Comment by fnky** [comment]
I have the same issue. You can enable Auto Imports by setting the `typescript.suggest.autoImports` to `true`.

What's odd is that your example with auto completing the import `acceptWebSocket` doesn't work at all for me. There's no suggestions showing up, whether the setting is on or off.

With this setting on, it also doesn't import the closest exports e.g. from a `deps.ts` file in the project, rather it tries to auto import it from the (cached) module path:

![auto-import-fail](https://user-images.githubusercontent.com/995050/74835366-0f0ab500-5315-11ea-813f-6e7d13a7787a.gif)

**Comment by axetroy** [comment]
v2.0.2 have been release.

feedbacks are welcome.

![1](https://user-images.githubusercontent.com/9758711/74848024-0abfb580-5370-11ea-8c65-e8027e356a0d.gif)

**Comment by Skillz4Killz** [comment]
@axetroy This issue is happening again to me.

![image](https://user-images.githubusercontent.com/23035000/76148024-4c3ea900-6070-11ea-870a-8bc604aea168.png)

![image](https://user-images.githubusercontent.com/23035000/76148026-5365b700-6070-11ea-99e3-b05f24c0f88f.png)

```ts
deno --version
deno 0.35.0
v8 8.1.310
typescript 3.8.2
```

**Comment by axetroy** [comment]
@Skillz4Killz 

Hi. For this function, I have written related test cases

https://github.com/axetroy/vscode-deno/blob/7cd9a554d7655b9b18535de59cbe94ee93260a3f/core/deno_normalize_import_statement.test.ts#L1-L40

And it works fine for me.

![截屏2020-03-0801 52 31](https://user-images.githubusercontent.com/9758711/76149899-8004e780-60df-11ea-900f-0426d28bd692.png)

Can you provide an example that doesn't work

**Comment by Skillz4Killz** [comment]
@axetroy https://github.com/Skillz4Killz/Discordeno-bot-template/blob/master/src/events/guild_create.ts

If you clone this simple example repo, run deno fetch and try to set `guild` to `guild: Guild`  with autocomplete it breaks.
