### ISSUE TITLE
regression: (1.19.0+) Cannot resolve export * from

### ISSUE THREAD

**Issue by brandonkal** [axetroy/vscode-deno#47]
### test

```ts
import * as rt from 'https://deno.land/x/lib/runtypes.ts'

const Config = rt.Record({
  domain: rt.String,
  publicIP: rt.String,
})
```

**Describe the bug**

The last working version is 1.18.0, after that the code above displays errors such as:
```
Property 'Record' does not exist on type 'typeof import("/home/brandon/.cache/deno/deps/https/deno.land/x/lib/runtypes")'.
```

I would guess it was introduced in this commit: https://github.com/axetroy/vscode-deno/commit/ffe30fb

**To Reproduce**

1. Create new file with contents above
2. Execute it to ensure the files are downloaded
3. Observe the errors
4. Observe errors do not exist in 1.18.0.

**Expected behavior**

No TypeScript errors here.

**Screenshots**

**Versions**

vscode: 1.42.0
deno: 0.32.0
extension: 1.19.0 - 1.21.0

**Comment by axetroy** [comment]
Hi. I think this bug has been fixed

If you still have this problem, reopen the issue

**Comment by brandonkal** [comment]
Confirmed fix. Thanks!
