### ISSUE TITLE
error when module does not exist

### ISSUE THREAD

**Issue by brandonkal** [axetroy/vscode-deno#5]
If a module doesn't exist the standard TypeScript compiler error leaks through i.e. "Imports cannot end in ".ts", consider removing it."

I'm not sure if it is possible for a TypeScript plugin to change error output to something more useful. If not, one hacky solution would be to change the import to some `.js` file that is known to not exist.
```
import from './mod.ts' ==> import from './mod.ts.missing.js'
```

**Comment by David-Else** [comment]
If I have a `.deps` file like this:
```
export { createRequire } from 'https://deno.land/std/node/module.ts';
```
It also has `An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/std/node/module' instead.ts(2691)`. Is this the same bug/limitation?

```
Name: Deno
Id: axetroy.vscode-deno
Description: Deno support for VSCode
Version: 1.9.0
Publisher: axetroy
```

**Comment by brandonkal** [comment]
If you haven't run deno fetch on the file and reopened it then yes.

**Comment by David-Else** [comment]
@brandonkal Thanks, I did fetch the resources and reopened VS Code and the errors went away :) 

A correct warning message would be very helpful, and/or not having to reload would avoid some confusion.

**Comment by axetroy** [comment]
@David-Else 

Theoretically, this does not require reopening vscode after you fetch resources.

This error really should not be

This is a built-in Typescript error and I am trying to filter it out

**Comment by axetroy** [comment]
![截屏2020-01-2922 56 01](https://user-images.githubusercontent.com/9758711/73367538-a4082880-42ea-11ea-81b4-7cfe6b659ed2.png)
![截屏2020-01-2922 56 12](https://user-images.githubusercontent.com/9758711/73367540-a4a0bf00-42ea-11ea-9f73-4b5b6812d9f2.png)


I think I have solve this problem temporarily.

It ’s not perfect, but it works.

**Comment by David-Else** [comment]
Thanks for all the great work! There is strange behavior now (better than before), but is this expected?

```
const entireEslintConfig = await runCommandReturnResults([]);
```
When VS Code can't find `await runCommandReturnResults()` it correctly finds the export in `./utils.ts` and asks to creates the import, but it then creates a `.js` extension instead of the `.ts`. The program does not work, so I rename it to `.ts` and it does work.
```
import { runCommandReturnResults } from "./utils.js"; // < REAL file is utils.ts!

const entireEslintConfig = await runCommandReturnResults([]);
```
I understand you are working around problems with TypeScript itself, I hope they will resolve this nonsense soon! :)

**Comment by brandonkal** [comment]
Yep. That's because this extension has to hide the fact that the file actually contains ".ts" imports from TypeScript. Hopefully they will eventually stop giving special treatment to that file extension.
