### ISSUE TITLE
Utilise TS 3.8 language extension auto import

### ISSUE THREAD

**Issue by kitsonk** [axetroy/vscode-deno#65]
I figured this feature in TS 3.8 would be useful: https://github.com/microsoft/TypeScript/pull/36725

**Comment by axetroy** [comment]
Hi.

I researched this new feature and it seems to work on the following APIs

```ts
tsserver.getCompletionEntryDetails()
tsserver.getCodeFixesAtPosition()
tsserver.getCombinedCodeFix()
tsserver.getApplicableRefactors()
tsserver.getEditsForRefactor()
tsserver.organizeImports()
```

This doesn't seem to help the extension.

Thank you for telling me this. 🍻
