### ISSUE TITLE
Allow Imports With .ts Files

### ISSUE THREAD

**Issue by Skillz4Killz** [axetroy/vscode-deno#70]
#41 

There was no way for me to reopen that issue so I opened a new one to discuss it farther. 

![image](https://user-images.githubusercontent.com/23035000/75055961-fda3e300-54a3-11ea-8807-1f50c117b122.png)

![image](https://user-images.githubusercontent.com/23035000/75056024-1f04cf00-54a4-11ea-8a55-496b9a51d55f.png)

Things I have tried:
1. Modified the file.
2. Reloaded the extension.
3. Restarted VSC entirely.
4. Uninstalled and reinstalled extension (reload/restart again)

**Comment by axetroy** [comment]
I got it.

BTW. This extension has not worked well in deno v0.34.0 in recent days

The change of Deno will take me a days to adapt it

**Comment by Skillz4Killz** [comment]
Has there been any update on this @axetroy Sadly my project is at a standstill as I am unable to code since importing anything makes it become an error or `any` if I ignore the error. Making it `any` basically makes me lose all the benefits of TS and makes development much harder. Has Deno patched this issue yet?

**Comment by axetroy** [comment]
@Skillz4Killz current progress see https://github.com/denoland/deno/issues/4069 discussions

**Comment by axetroy** [comment]
Hi!

vscode-deno@3.0.0 have been release. can you try it again?

**Comment by Skillz4Killz** [comment]
Can confirm this is indeed working.
