### ISSUE TITLE
Could not find <URL> locally

### ISSUE THREAD

**Issue by KSXGitHub** [axetroy/vscode-deno#74]
### test

**Describe the bug**

When I try to import https://raw.githubusercontent.com/denoland/deno/v0.34.0/std/path/mod.ts, the language server tell me that it could not find locally

**To Reproduce**

1. Create `./types/deno.d.ts`

```sh
mkdir types
deno types > ./types/deno.d.ts
```

2. Create `.vscode/settings.json`

```json
{
  "deno.enable": true,
  "deno.dts_file": ["./types/deno.d.ts"]
}
```

3. Create `lib/mymodule.ts`

```typescript
import {} from 'https://raw.githubusercontent.com/denoland/deno/v0.34.0/std/path/mod.ts'
```

4. Fetch all dependencies

```sh
deno fetch lib/mymodule.ts
```

**Expected behavior**

No errors

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/11488886/75344242-d21e5f80-58cc-11ea-9461-3e30e04de301.png)

**Versions**

vscode: 1.42.1
deno: 0.34.0
extension: latest from marketplace

**Comment by axetroy** [comment]
close. ref: #67
