### ISSUE TITLE
Could not find module locally

### ISSUE THREAD

**Issue by StefanoPernat** [axetroy/vscode-deno#77]
### test

**Describe the bug**

When I tried to import a random module language server says "Could not find module locally"

**To Reproduce**

1. Create `.vscode/settings.json`
```json
{
  "deno.enable": true
}
```
Tried also to set **deno.dts_file** setting but nothing changed

2. Create `file.ts` 
```typescript
import { v4 } from "https://deno.land/std/uuid/mod.ts";

console.log(v4.generate())
```
Tried also perform **deno fetch** but got same result

**Expected behavior**

No error from language

**Screenshots**

<img width="716" alt="Schermata 2020-02-29 alle 10 08 18" src="https://user-images.githubusercontent.com/9131699/75605047-72e46900-5adf-11ea-838a-a1b0cae6956d.png">

Also noticed that if I type the module address I got as suggestion some adresses that seems some kind of hash

<img width="680" alt="Schermata 2020-02-29 alle 10 09 33" src="https://user-images.githubusercontent.com/9131699/75605074-c951a780-5adf-11ea-9000-202e7ffa0f68.png">

**Versions**

vscode: 1.42.1
deno: 0.34
extension: 2.0.4
OS: macOS Catalina

**Comment by axetroy** [comment]
close. ref: #68
