### ISSUE TITLE
Extension doesn't recognize exports from modules

### ISSUE THREAD

**Issue by xpyxel** [axetroy/vscode-deno#79]
### Extension doesn't recognize exports from modules

**Describe the bug**

When importing modules such as `https://deno.land/std/fmt/mod.ts` it recognizes the local cached file, however fails to resolve anything within the module such as `fmt.green()`. 

**To Reproduce**

1. Make sure you're on Deno v0.35.0
2. Import a module such as `https://deno.land/std/fmt/mod.ts` and make sure it's cached
3. Try to import a function / etc from the cached module

**Expected behavior**

It should successfully resolve the module, not showing an error.

**Screenshots**

![screenshot](https://owo.sh/55Kb1Qm.png)

**Versions**

vscode: 1.42.1
deno: 0.35.0
extension: 3.0.1

**Comment by xpyxel** [comment]
When using `console.log` to print the contents of `fmt` it results in

![screenshot](https://owo.sh/JDdvhib.png)

**Comment by axetroy** [comment]
![截屏2020-03-0113 26 39](https://user-images.githubusercontent.com/9758711/75620164-4fddb600-5bc0-11ea-8064-def9b03d271e.png)

It work fine for me.

try remove comments for `.vscode/settings.json`

**Comment by xpyxel** [comment]
@axetroy I have no comments in my `.vscode/settings.json` file, it consists of the following:

```json
{
    "deno.enabled": true,
    "editor.tabSize": 2,
    "[typescript]": {
        "editor.defaultFormatter": "axetroy.vscode-deno"
    },
    "[typescriptreact]": {
        "editor.defaultFormatter": "axetroy.vscode-deno"
    }
}
```

**Comment by axetroy** [comment]
I want to know, is it normal for other modules?

**Comment by xpyxel** [comment]
It works fine for local modules such as `./test.ts` but doesn't work with remote modules, i.e.: `https://deno.land/std/fmt/mod.ts`.

**Comment by axetroy** [comment]
I tried it in Windows and it works fine

If the Deno namespace is not found, it should be that typescript-deno-plugin has not been started

If you have `tsconfig.json` in your project directory please delete

see README

**Comment by xpyxel** [comment]
I did not have a `tsconfig.json` file, i'm gonna try to reinstall deno and the extension and see if it fixes it.

**Comment by axetroy** [comment]
@xpyxel a new version have been released and it has fix some issues in Windows

**Comment by xpyxel** [comment]
yeah seems to be fixed now, closing this, thanks for your work @axetroy.
