### ISSUE TITLE
bundle extension

### ISSUE THREAD

**Issue by brandonkal** [axetroy/vscode-deno#87]
Looking at the CI logs I see:

This extension consists of 1589 files, out of which 1112 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore

That is a LOT of files for what this extension does. It will be worth investigating what artifacts actually is not required and then bundling the extension with rollup for better performance.

**Comment by axetroy** [comment]
I have some other extensions. I tried to use a tool like `webpack`/`ncc` to pack extensions into a single file.

It really reduces the size of the expansion and improves the loading speed.

To be honest, I don't really like `webpack`

And `webpack` will make the workflow extremely complicated and brings me more bugs.

So, I will ignore this warning & thanks for your feedback
