### ISSUE TITLE
can't format new unsaved files - extension deno cannot format '/untitled-1'

### ISSUE THREAD

**Issue by David-Else** [axetroy/vscode-deno#93]
```
code --version
1.43.0
```
```
  "[javascript]": {
    "editor.defaultFormatter": "axetroy.vscode-deno"
  },
  "[typescript]": {
    "editor.defaultFormatter": "axetroy.vscode-deno"
  },
```
`ctrl-n` a typescript file, ctrl+shift I to format, `extension deno cannot format '/untitled-1'` appears as message

**Comment by axetroy** [comment]
In theory, Extension can support untiled documents formatting

But this will increase the complexity of the extension and the scene is not commonly used

And many modules depend on file paths, eg `dependency query`/`code diagnosis` ...

So I don't think it is necessary, thank you for your feedback
